SM-1247 Add Login With DIMO
DIMO-Network/trips-web-app pull request #43
Opened 2024-11-07 19:51 UTC by lauradeng23

# Proposed Changes

### Impacted Pages

### Caveats

2024-11-07 20:44 UTC, JamesReate commented on app-login/src/App.tsx
> +                  apiKey={"529070feb71020afc2dfa7c34815bae38b993e3c822cc9b96fbc9df86f2937c6"}
is this ok to be visible @Asfiroth

2024-11-08 11:50 UTC, Asfiroth requested changes

2024-11-08 11:50 UTC, Asfiroth commented on app-login/src/App.tsx
> +                  clientId={"0xf5ada890DA2E5582E38DF4648F9dAeE00e691199"}
this should come from env variables

2024-11-13 18:48 UTC, JamesReate approved these changes

2024-11-13 19:08 UTC, merged